### ISSUE TITLE
Update to Node 17

### ISSUE THREAD

**Issue by bt95** [uhop/node-re2#120]
Hello!

I use `re2` library in a project and we want to update to Node v17, which [was released in October](https://nodejs.org/en/blog/release/v17.0.0/). When trying to build the project using Node v17 this error shows up: 
![image](https://user-images.githubusercontent.com/28559498/144619846-ec5e4eac-2b51-4c4f-ad61-dcd7e08b2dff.png)

Thanks!

**Comment by uhop** [comment]
At least every major version Node changes [ABI](https://en.wikipedia.org/wiki/Application_binary_interface). Essentially its internal API changes, which requires recompilation of binary modules. `re2` is a binary module based on a C++ library.

As per the error above, it is not sufficient to run a different version of Node in the same application directory, which was initialized by a different Node version. You should run `npm i`, which, in turn, will recompile necessary modules.

Theoretically, it can happen with pure JS code as well, but usually don't because:

* JS is a dynamic language and binds to APIs on the fly, unlike static C++.
* The Node team is reasonably conservative and does not change/remove JS API abruptly supporting old versions for a long time. Otherwise, JS programs would break more frequently.

So:

* Run `npm i` with a new version of Node.
* In some cases it helps to remove `node_modules` before running `npm i`.

**Comment by uhop** [comment]
I added a precompiled version for Node 17 in 1.17.0, which will be published shortly.

**Comment by bt95** [comment]
Thanks a lot for help and for the clear instructions provided.
