### ISSUE TITLE
fallback to node-gyp if download fails

### ISSUE THREAD

**Issue by viceice** [uhop/node-re2#81]
Hi

is it possible to fallback to a node-gyp local build if the download fails?

As on of our users is behind a corporate proxcy, which seems to block that download.

ref: renovatebot/docker-renovate#44

**Comment by uhop** [comment]
That is strange because an unsuccessful download should trigger a build automatically. Could you investigate more?

Nevertheless, in order to skip downloading a precompiled asset and to force a local build all you need is to define an environment variable as instructed in https://github.com/uhop/node-re2/wiki/Problem:-ABI-mismatch-in-Electron

**Comment by viceice** [comment]
Thanks, i'll forward those information.

**Comment by uhop** [comment]
I looked at your reference and I don't see any obvious problems. You may hit some `yarn` incompatibility: https://github.com/uhop/node-re2/wiki/Problem:-unusual-errors-with-yarn

**Comment by viceice** [comment]
Ok, yes i've seen this yarn issue sometimes, a force install had always fixed that
