### ISSUE TITLE
Exposing never_capture and max_mem options

### ISSUE THREAD

**Issue by kzar** [uhop/node-re2#83]
# Background

The upcoming [declarativeNetRequest](https://developer.chrome.com/extensions/declarativeNetRequest) extension API in Chrome will eventually (more or less) replace the old webRequest API for ad blocking and similar extensions. You supply the API with blocking rules, then Chrome itself takes care of enforcing them by blocking matching requests. The API also supports matching requests using regular expressions, but with the RE2 engine and with a memory limit of 2kb per regular expression.

There is now the [declarativeNetRequest.isSupportedRegex](https://developer.chrome.com/extensions/declarativeNetRequest#method-isRegexSupported) function which allows us to see if a given regular expression will work at run time in the browser, but so far we don't have an equivalent way to check regular expressions in Node.js at build time. For that we need to be able to call `options.set_max_mem` and `options.never_capture` [like the Chromium code does](https://source.chromium.org/chromium/chromium/src/+/master:extensions/browser/api/declarative_net_request/utils.cc;l=231-252).

# What to change

Provide an interface for optionally specifying the memory limit, never_capture and possibly other RE2 options when constructing a RE2 object:

      new RE2(pattern[, flags, options])

**Comment by uhop** [comment]
My notes:

1. The goal of this project is not an interface to `RE2` the C++ library, but to create a drop-in replacement for existing regular expression objects that uses `RE2` as its engine. Obviously we cannot replicate (and don't want to do it) the standard `RegExp` 100%, but while the implementation differs, the API is more or less the same. No changes to existing methods or properties, maybe some extended interpretation at most. That's why I am hesitant to add a non-standard 3rd parameter to the constructor.
   * Having said that, it may make some sense to provide an interface to `RE2` without any compatibility with `RegExp`.
2. Your statement above does not convey the ultimate goal and why it is important. What are we trying to achieve here? Correct me if I am wrong, but it looks like it is for a super narrow case of supporting a project, which wants to emulate some non-standard (yet?) networking I/O behavior in Chrome. The document itself does not propose to change `RegExp` in any way.
3. Their code:
   1. ...switches `RE2` from UTF-8 to Latin1, which will break `node-re2`:
      * All JavaScript strings are UTF-16 based. It can be translated to UTF-8 but not to Latin1, which is the extended ASCII.
        * All string conversions/operations in `node-re2` work with UTF.
      * TBH, they do that only for efficiency, so functionally-wise it can be ignored.
   2. The same goes for `never_capture()`, which will break user's expectations.
      * It means that such regular expressions can be used only for verification, not for parsing.
      * TBH, they do that only for efficiency, so functionally-wise it can be ignored.
   3. Limiting the size of memory per regular expression is more interesting, and it doesn't affect the glue-code provided by `node-re2`.
      * This is something to be considered. I suggest to provide a separate API for that, e.g., a property that can be set, or an alternative factory function/constructor.

So as I see it, we have two possible ways to handle, providing it makes sense to implement at all:

1. Special constructor or some equivalent. Possible example:
   ```js
   const RE2 = require('re2');
   const extRegExp = new RE2.Ext(/\d/, 'i', {maxMemory: 2048});
   ```
2. Or provide a separate API to RE2 bridging native methods and properties:
   * No translation of regular expressions.
   * No translation of strings (buffers only?).
     * It will allow to use Latin1 directly.
   * No adapting signatures.
     * Minimal conversion of input parameters.
     * Minimal conversion of output.

Both approaches break "a drop-in replacement for existing regular expressions" philosophy. The code that use them become RE2-specific.

The first approach still capitalizes on a familiar well-documented `RegExp` API.

Obviously the second option is much harder to implement and requires designing the API first.

What are your thoughts and comments?

**Comment by kzar** [comment]
> Your statement above does not convey the ultimate goal and why it is important.

The ultimate goal is for Adblock Plus and similar ad blocking extensions to be able to continue supporting regular expression filters after Chrome has switched to the new declarativeNetRequest API.

To achieve that goal the extensions need to be able to determine if a given regular expression will be supported by the declarativeNetRequest API at build-time, and so will need to be ale to control the options passed to RE2 from Node.js such as max_mem.

For example, an Adblock Plus filter such as

      /example/

would become

```
[
{
	"priority": 1000,
	"condition": {
		"regexFilter": "example",
		"isUrlFilterCaseSensitive": false
	},
	"action": {
		"type": "block"
	},
	"id": 1
}
]
```
but only if we can verify that the regular expression "example" will be supported by the declarativeNetRequest API.

This is important since ad blocking extensions for Chrome which many millions of users use will eventually have to use the declarativeNetRequest API to block requests. They will likely need to convert Adblock Plus style filters into declarativeNetRequest rules at build time. We need support for as many Adblock Plus style filers as possible to give the best ad blocking experience.

> The goal of this project is not an interface to RE2 the C++ library...

Fair enough, I had assumed it was especially given the name. If you don't think this use case of directly interfacing with RE2 is a fit for this library I can take another approach.

**Comment by kzar** [comment]
By the way, if you have the time would you mind taking a quick look at the pull request anyway? I don't think my approach for pulling `max_mem` and `never_capture` out of the extra options is quite right, I'm seeing CI failures. I would be curious to know where I went wrong as I'm still getting my head around this stuff!

**Comment by kzar** [comment]
I'm going to use RE2 directly with node-gyp etc. Feel free to close this if you like.

**Comment by uhop** [comment]
If I understood correctly, all you need is to make sure that regular expressions from a list conform to certain criteria, e.g., `max_mem`. Personally I would write a tiny C++ utility for that using RE2 to verify expressions. No JavaScript complications are needed. This utility can be launched from Node using [child process](https://nodejs.org/api/child_process.html), if that's your desire.
