### ISSUE TITLE
Problem with re2.node in Freebsd12.1/Kibana7

### ISSUE THREAD

**Issue by kapunov81** [uhop/node-re2#93]
Module re2.node don't work in fresh installation of Freebsd12.1 and KIbana7 (function regex in timelion visualisations):
![2](https://user-images.githubusercontent.com/78531195/107116344-1e16aa00-687b-11eb-998a-6acc44812ce2.jpg)
This is the result of running verify-build.js, that comes with re2 module:
#:/usr/local/www/kibana7/node_modules/re2/scripts# node ./verify-build.js
internal/modules/cjs/loader.js:807
return process.dlopen(module, path.toNamespacedPath(filename));
^

Error: /usr/local/www/kibana7/node_modules/re2/build/Release/re2.node: invalid file format
at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
at Module.require (internal/modules/cjs/loader.js:692:17)
at require (internal/modules/cjs/helpers.js:25:18)
at Object. (/usr/local/www/kibana7/node_modules/re2/re2.js:3:13)
at Module._compile (internal/modules/cjs/loader.js:778:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Module.load (internal/modules/cjs/loader.js:653:32)

Version of Node - 10.6.14.8
Openjdk - 11.0.10
Kibana - 7.10.1

**Comment by uhop** [comment]
RE2 is a binary extension written in C++ and, as such, it would be compiled. Usually, a compiler sniffs the capabilities of a build platform and can generate a platform-specific code. In general, it happens when a Docker build was done on an incompatible computer. Examples:

1. A Docker image was built on ARM and later ran on Intel/AMD.
2. A Docker image was built on a developer's laptop with one Intel processor supporting one set of features, then run on a VM with a different set of features. Specifically missing some CPU extensions available on the laptop.

It happened to me before with some binary utilities (no connection to node or npm at all). There are two ways to remedy this problem:

* Run `npm i` before starting your app, not when building an image.
* Build an image on a fully compatible computer, e.g., the same type of AWS VM instead of locally.

Please let me know if it helps you.

**Comment by kapunov81** [comment]
I found out that problem was in wrong version of re2.node, that comes with Kibana7 - and maintainer of this FreeBSD port will fix it in near future. Pending this fix I solved this problem of re2.node myself:
1) Created directory ./my_modules
2)cd ./my_modules
3)run #npm install --save re2
4)Copied obtained file ./my_modules/.../re2.node into /usr/local/www/kibana7/node_modules/re2/build/Release/ instead original re2.node
5) Got working timelion visualizations
![3](https://user-images.githubusercontent.com/78531195/107248943-7e544a00-6a3b-11eb-8572-a15901633900.jpg)
